### ISSUE TITLE
Error running san_eval.py 

### ISSUE THREAD

**Issue by zrqi** [D-X-Y/SAN#11]
I feel so sorry to bother you again.The following problems occurred when I  run the san_eval.py to tested the new image:
Traceback (most recent call last):
  File "san_eval.py", line 78, in <module>
    evaluate(args)
  File "san_eval.py", line 55, in evaluate
    batch_heatmaps, batch_locs, batch_scos, _ = net(inputs)
  File "/share/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/share/home/SAN/lib/models/itn_cpm.py", line 136, in forward
    batch_location, batch_score = find_tensor_peak_batch(cpm_stage3[ibatch], self.config.argmax, self.downsample)
  File "/share/home/SAN/lib/models/basic_batch.py", line 43, in find_tensor_peak_batch
    X = MU.np2variable(torch.arange(-radius, radius+1), heatmap.is_cuda, False).view(1, 1, radius*2+1)
  File "/share/home/SAN/lib/models/model_utils.py", line 16, in np2variable
    raise Exception('Do not know this type : {}'.format( type(x) ))
Exception: Do not know this type : <class 'torch.Tensor'>
Does the mistake come from the pytorch?

**Comment by D-X-Y** [comment]
Would you mind to provide your testing script and the image?

**Comment by zrqi** [comment]
I just use the san_eval.py to detect the test_1.jpg

**Comment by D-X-Y** [comment]
Hi, I just fix this bug, sorry for the inconvenience.
