### ISSUE TITLE
Error on running cluster.py

### ISSUE THREAD

**Issue by td042** [D-X-Y/SAN#2]
While running the command "sh scripts/300W/300W_Cluster.sh 0,1 GTB 3" I got the following error message:

Traceback (most recent call last):
  File "cluster.py", line 232, in <module>
    main()
  File "cluster.py", line 58, in main
    resnet = models.resnet152(True, num_classes=4)
AttributeError: module 'models' has no attribute 'resnet152'

Do you have any idea what I did wrong?

**Comment by D-X-Y** [comment]
Hi, the model codes and training codes are not included in the current project. I'm still re-organizing them, and plan to release the full code before 1st June.
