### ISSUE TITLE
"cluster.py"  No module named 'models'

### ISSUE THREAD

**Issue by biyuehuang** [D-X-Y/SAN#4]
hello，when I run $sh scripts/300W/300W_Cluster.sh 0,1 GTB 3. There is no 'models'. Is it missing the models.py ? Thanks.

$ sh scripts/300W/300W_Cluster.sh 0,1 GTB 3
script name: scripts/300W/300W_Cluster.sh
3 arguments
Traceback (most recent call last):
  File "cluster.py", line 23, in <module>
    import debug, models, options
  File "/home/hy/exercise/semantic_segmentation/SAN/lib/debug/__init__.py", line 1, in <module>
    from .debug_main import main_debug_save
  File "/home/hy/exercise/semantic_segmentation/SAN/lib/debug/debug_main.py", line 6, in <module>
    import models
ModuleNotFoundError: No module named 'models'

**Comment by D-X-Y** [comment]
Yes, the models and procedure directories in 'lib' will come soon in one month.

**Comment by biyuehuang** [comment]
Thanks a lot！You are so kind generous.

**Comment by biyuehuang** [comment]
Thanks a lot! You are so generous.
